version: "3"

services:
  web:
    build: .
    command: python3 manage.py runserver 0:8000
    ports:
      - "20100:8000"
    volumes:
      - .:/web
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
